import type { Metadata } from "next";
import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";

const FamiljenGrotesk = Familjen_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-famijen-grotesk",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const user = session?.user;

  console.log(user);

  return (
    <html lang="en">
      <body className={`${FamiljenGrotesk.variable} antialiased`}>
        <Header user={user} />
        <div className="w-full pr-4 pl-4 pb-16">{children}</div>
      </body>
    </html>
  );
}
